import type { NextPage } from 'next'
// import Image from 'next/future/image'
import Head from 'next/head'
import styles from './Home.module.css'
import Header from '@/components/sections/header'
import Footer from '@/components/sections/footer'
import Hero from './components/hero'
import Hub from './components/hub'

const Home: NextPage = () => {
  return (
    <div className={styles.homepage + '  min-h-screen'}>
      <Head>
        <title>Nibiru</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main>
        <Hero />
        <Hub />
        {/* <Image
          className="absolute right-5 -bottom-[10vh] z-40 w-[30vw]"
          src="/images/gems.png"
          alt="Nibiru's gems"
          width={565}
          height={779}
        /> */}
      </main>
      <Footer />
    </div>
  )
}

export default Home
