name: Deploy Preview

on: pull_request

jobs:
  build_and_deploy:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          expires: 7d
          projectId: nibiru-chain
